### ISSUE TITLE
Try to make sure GTK2 support can build

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#27]
According to @mattatobin GTK2 was busted right before our fork-off point.

We should investigate:
- What was busted and why
- How it can be repaired *without* backing out all the XPCOM changes that are cross-platform and likely pivotal to the platform's current state.

**Comment by mattatobin** [comment]
Pretty much will/is solved in `Take 2`

**Comment by wolfbeast** [comment]
Not solved yet in UXP, but part of that is something that's still slated to be changed (Not using Skia for content).
